### ISSUE TITLE
Inheritance support

### ISSUE THREAD

**Issue by alexsotocx** [yammer/model_attribute#9]
Hello I'm facing the issue with inheritance, attributes are not being copied.

Ruby 2.3.1
model_attribute (3.1.1)

```ruby
require 'model_attribute'
class Person
  extend ModelAttribute
  attribute :name,       :string
  attribute :last_name,       :string

  def initialize(attributes = {})
    set_attributes(attributes)
  end
end


class User < Person

  def initialize(attributes = {})
    super(attributes)
    self.name = "This is an error"
  end
end


User.attributes # nil
User.new({})

# /Users/soto/.rvm/gems/ruby-2.3.1/gems/model_attribute-3.1.1/lib/model_attribute.rb:87:in `read_attribute': undefined method `include?' for nil:NilClass (NoMethodError)
# 	from /Users/soto/.rvm/gems/ruby-2.3.1/gems/model_attribute-3.1.1/lib/model_attribute.rb:66:in `write_attribute'
# 	from /Users/soto/.rvm/gems/ruby-2.3.1/gems/model_attribute-3.1.1/lib/model_attribute.rb:27:in `name='
# 	from script.rb:17:in `initialize'
# 	from script.rb:22:in `new'
# 	from script.rb:22:in `<main>'
```

**Comment by dwaller** [comment]
Hi @alexsotocx, thanks for raising the issue.  

I vaguely recall running into this issue a long time ago (two years ago) and setting out to fix it.  I don't fully recall why I stopped, but I think I found that it was harder than I had thought to define what the desired behaviour actually was!  If you would like to have a go, feel free to create a PR that defines and implements some sensible behaviour (don't forget rigorous specs!).  You might want to start with my aborted attempt: 1f42a274f769b098dbea0072a96deaa0b35f8371.
